### ISSUE TITLE
Code Quality Improvements

### ISSUE THREAD

**Issue by GrahamCampbell** [thephpleague/factory-muffin#180]
I'm just going to note down a few improvements that could be made.
We can tick them off as we do them:
- [x] `Generators\Call::generate` should be broken up (Complete: #196)
- [x] `Generators\Generic::generate` should be broken up (Complete: #196)
- [x] `Factory::deleteSaved()` should be broken up (Complete: #197)
- [x] The 4th case can be removed from `Facade::__callStatic()` since that optimisation isn't needed because all methods only accept up to 3 parameters (Complete: #182)
- [x] Logical operators shouldn't be used in if statements (Complete: #181)

_Those marked as checked are implemented now._
